[package]
name = "clipimg"
version = "0.1.0"
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2018"

[dependencies]
arboard = "1.2.1"
image = "0.23.14"

[[bin]]
name = "clipimg"
path = "clipimg.rs"
